[package]
name = "reverse-tunnel-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
rcgen = "0.14"
rustls-pemfile = "2"
socket2 = "0.6"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "io-util", "time"] }
tokio-yamux = "0.3.20"
tunnel-core = { path = "../tunnel-core" }
tokio-rustls = "0.26"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
proptest = "1"
